name: Convert README to PDF

on: [push]

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: mkdir output
      - uses: maxheld83/pandoc@v2
        with:
          args: "--pdf-engine=xelatex --output=output/resume.pdf resume.md"
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
