name: Convert Markdown to PDF

on:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Pandoc generator
      uses: Lothindir/pandoc-markdown-action@v0.4
      with:
        markdown: resume.md
        pdf: resume.pdf
        template: # optional, default is none 
